version: '3'

services:
  database:
    image: mongo 
    ports:
      - "27017:27017"
  web:
    image: b2w
    environment:
      - ENV=prod
    links:
      - database
    ports:
      - "8000:8000"
    depends_on:
      - database
