version: '3'

services:
  database:
    image: mongo 
    ports:
      - "27017:27017"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    links:
      - app
    depends_on:
      - app

  app:
    image: b2w
    environment:
      - ENV=prod
    links:
      - database
    ports:
      - "8000:8000"
    depends_on:
      - database
